# Generated by Django 5.2.4 on 2025-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.ImageField(upload_to='Projects/')),
                ('New_update', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approved_Projects', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('Pasword', models.BigIntegerField()),
                ('User_id', models.CharField(max_length=50)),
            ],
        ),
    ]
