# Generated by Django 5.2.4 on 2025-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.ImageField(upload_to='projects/')),
                ('Approved_Projects', models.TextField()),
                ('New_Projects', models.TextField()),
            ],
        ),
    ]
