# Generated by Django 5.2.4 on 2025-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
