# Generated by Django 5.2.4 on 2025-09-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_detail',
            old_name='Pasword',
            new_name='Password',
        ),
    ]
