# Generated by Django 5.2.4 on 2025-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0002_rename_pasword_pdf_detail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_detail',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
