# Generated by Django 5.2.4 on 2025-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0003_alter_pdf_detail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_project',
            name='Image_url',
            field=models.ImageField(default='null', upload_to='Projects/'),
        ),
    ]
