# Generated by Django 5.2.4 on 2025-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0004_alter_new_project_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_project',
            name='Image_url',
        ),
        migrations.AddField(
            model_name='pdf_detail',
            name='Image_url',
            field=models.ImageField(default='null', upload_to='Projects/'),
        ),
        migrations.AddField(
            model_name='pdf_detail',
            name='is_delete',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pdf_detail',
            name='Password',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf_detail',
            name='User_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
