# Generated by Django 5.2.4 on 2025-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0005_remove_new_project_image_url_pdf_detail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_detail',
            name='Password',
            field=models.CharField(db_collation='utf8_bin', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf_detail',
            name='User_id',
            field=models.CharField(db_collation='utf8_bin', max_length=50, unique=True),
        ),
    ]
