# Generated by Django 5.2.4 on 2025-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0006_alter_pdf_detail_password_alter_pdf_detail_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
