# Generated by Django 5.2.4 on 2025-09-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0007_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
