# Generated by Django 5.2.4 on 2025-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0008_userdata_delete_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_detail',
            name='Image_url',
            field=models.ImageField(null=True, upload_to='Projects/'),
        ),
        migrations.AlterField(
            model_name='pdf_detail',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
