# Generated by Django 5.2.4 on 2025-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0009_alter_pdf_detail_image_url_alter_pdf_detail_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_detail',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
    ]
