# Generated by Django 5.2.4 on 2025-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0010_alter_pdf_detail_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.0005555555555555556),
            preserve_default=False,
        ),
    ]
