# Generated by Django 5.2.4 on 2025-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0012_remove_pdf_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='9/8/2025'),
            preserve_default=False,
        ),
    ]
