# Generated by Django 5.2.4 on 2025-09-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0013_pdf_detail_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_detail',
            name='created_at',
        ),
    ]
