# Generated by Django 5.2.4 on 2025-09-08 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0014_remove_pdf_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 6, 12, 0)),
            preserve_default=False,
        ),
    ]
