# Generated by Django 5.2.4 on 2025-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0016_remove_pdf_detail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-08 12:34:56'),
            preserve_default=False,
        ),
    ]
