# Generated by Django 5.2.4 on 2025-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govapp', '0017_pdf_detail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
